### ISSUE TITLE
makemigrations gives: module 'django.db.models' has no attribute 'UnixTimeStampField'

### ISSUE THREAD

**Issue by MonsieurCellophane** [myyang/django-unixtimestampfield#5]
Please disregard the description below - I'm embarassed of having only now realized 
 that I was using `models.UnixTimeStampField `rather than `UnixTimeStampField`. I am leaving the description for historical purposes. I do, however believe that instructions on usage in settings.py are in order. Thank you for your work.

ORIGINAL DESCRIPTION BELOW - DISREGARD.

I initially got the error with django 3.0.4, but upgrading to 3.0.8 made no difference. It may be due to something missing in settings (the documentation says nothing about settings for this module, and I think that should be fixed). As things are, I just stuck unixtimestampfield in INSTALLED_FIELDS and flipped an integerfield in a  formerly working models.py to UnixTimeStampField - hence the error. Changing the position in INSTALLED_APPS make no difference.

**Comment by myyang** [comment]
don't mind. I'll close this then.
