### ISSUE TITLE
Add Django 4 Support

### ISSUE THREAD

**Issue by ownerni** [myyang/django-unixtimestampfield#6]
Hi, We are using unixtimestampfield with the recently release Django 4 version, please update your package to support Django 4, this is the error which we are getting:
```
from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'
```

**Comment by myyang** [comment]
hmmm... after reviewing the usage of translation,  I'll remove the translation part. Thanks for reporting.
